
package com.masikkk.jws.client.json;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JsonServiceImplService", targetNamespace = "http://json.server.jws.masikkk.com/", wsdlLocation = "http://localhost:8899/JsonService?wsdl")
public class JsonServiceImplService
    extends Service
{

    private final static URL JSONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException JSONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName JSONSERVICEIMPLSERVICE_QNAME = new QName("http://json.server.jws.masikkk.com/", "JsonServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8899/JsonService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JSONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        JSONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public JsonServiceImplService() {
        super(__getWsdlLocation(), JSONSERVICEIMPLSERVICE_QNAME);
    }

    public JsonServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JSONSERVICEIMPLSERVICE_QNAME, features);
    }

    public JsonServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, JSONSERVICEIMPLSERVICE_QNAME);
    }

    public JsonServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JSONSERVICEIMPLSERVICE_QNAME, features);
    }

    public JsonServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JsonServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JsonServiceImpl
     */
    @WebEndpoint(name = "JsonServiceImplPort")
    public JsonServiceImpl getJsonServiceImplPort() {
        return super.getPort(new QName("http://json.server.jws.masikkk.com/", "JsonServiceImplPort"), JsonServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JsonServiceImpl
     */
    @WebEndpoint(name = "JsonServiceImplPort")
    public JsonServiceImpl getJsonServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://json.server.jws.masikkk.com/", "JsonServiceImplPort"), JsonServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JSONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw JSONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return JSONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
