
package com.masikkk.jws.client.json;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JsonServiceImpl", targetNamespace = "http://json.server.jws.masikkk.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JsonServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryJson", targetNamespace = "http://json.server.jws.masikkk.com/", className = "com.masikkk.jws.client.json.QueryJson")
    @ResponseWrapper(localName = "queryJsonResponse", targetNamespace = "http://json.server.jws.masikkk.com/", className = "com.masikkk.jws.client.json.QueryJsonResponse")
    @Action(input = "http://json.server.jws.masikkk.com/JsonServiceImpl/queryJsonRequest", output = "http://json.server.jws.masikkk.com/JsonServiceImpl/queryJsonResponse")
    public String queryJson(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
